### ISSUE TITLE
Collecting resources from older project attempts

### ISSUE THREAD

**Issue by AzatothTheAwakened** [Together-Java/TJ-Bot#16]
To not forget valuable ideas coming from the community or other back then moderators, I'd like to start a discussion and review of older resources. That way, we can collect ideas that are still applicable today.
The following resources are to be reviewed:
- Collection of Ideas and Methods including projects like this: https://github.com/AzatothTheAwakened/TJ-ideas/blob/master/TJ-Ideas.pdf
- Old contributing guidelines: https://github.com/Together-Java/TjBot/blob/master/CONTRIBUTING.md

**Comment by marko-radosavljevic** [comment]
I like this, what else is there that might be useful for this project? Everyone should add links to stuff they consider valuable.

[TJ-Ideas.pdf](https://github.com/AzatothTheAwakened/TJ-ideas/blob/master/TJ-Ideas.pdf) has a lot of things that we already solved, for example the whole Infrastructure chapter.
If you reduce it down to still relevant issues, you should submit a PR, and we can discuss it there. It certainly contains useful knowledge. 

I'm just not sure if the latex is the best format for this, maybe markdown would be easier for working with.

Another idea regarding documentation is to have another project within org just for the documentation that will automatically publish to github pages. There are also tools for generating html docs. 

I think it's a neat solution for user docs, since websites are usually more user-friendly and easier to navigate compared to files on github. I think I will open an issue for this, so we can discuss it separately.

**Comment by Zabuzard** [comment]
Seems nobody has any resources floating around anymore and we will just add more stuff while we find it.
