### ISSUE TITLE
Which CI/CD pipeline integrations to use?

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#19]
I think using github workflows for our CI/CD is best for our use-case. It's very simple, powerful enough, free, and it's right here, integrated. 

Some of the tools that I think are worthy of considering for our pipeline:
- [Spotless](https://github.com/diffplug/spotless) for checking code style violations, and fixing them all with a single command.
- [Sonarlint](https://www.sonarlint.org/) / [Sonarqube](https://www.sonarqube.org/) for static analysis.
- [CodeQL](https://github.com/github/codeql) for security checks.

We can also use some github actions to help with moderation, an example would be [closing stale issues](https://github.com/marketplace/actions/close-stale-issues).

**Comment by AzatothTheAwakened** [comment]
Im a big fan of Sonarqube I definetly second this

**Comment by RicardoMonteiroSimoes** [comment]
Having some experience with GitHub actions I'd say using them is the easiest way of going about it. What I'd suggest for such an open repository:

- linting check on PRs
- check changes? PRs that are too big should probably be a big no no, as maintainability drops quite drastically
- Automatically run tests/compilation, request fixes if not passing
- I'm not sure how easy it is to do, but check if the _changes_ are covered with tests. I've had this idea in the back of my head for quite some time, but haven't really bothered searching for solutions to this. It would help by reducing pipeline time (i.e. instead of testing everything, start with changes, and then once reviews etc. are done, run once on all tests) and increase code quality

**Comment by marko-radosavljevic** [comment]
Thanks for joining us! ^^

What we have so far:
 - spotless - autoformatting on every compile/build
 - sonalint - static analysis
 - codeql - security analysis

We will integrate sonarcloud today too, which is much more powerful compared to sonarlint.

Things it can provide for us on each PR:

![image](https://user-images.githubusercontent.com/30927961/132678168-6fd2f513-338d-4158-a007-c970b2f9a27c.png)

Everything is configurable, so we can set the gate pass however we like it.

It also provides a really nice overview of the whole project. You can check other open-source projects and their sonarcloud, for example: [Brave](https://sonarcloud.io/dashboard?id=brave_brave-core).

And yeah, tests are the obvious choice. We just don't have any yet, so I haven't set it up. ^^

**Comment by RicardoMonteiroSimoes** [comment]
I saw you're using gradle. Got no experience with it, but I've used actions to compile to jar on any push to main, and then auto deploy. That's probably also a good idea?

**Comment by marko-radosavljevic** [comment]
That's still WIP, since we got the VPS just an hour ago, we still don't have a deployment strategy worked out. But there will surely be something like that.

Feel free to add if remember anything else :heart:

**Comment by Zabuzard** [comment]
Spotless, Sonarlint and CodeQL have been setup. Closing this.
