### ISSUE TITLE
Created a message for new contributes

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#299]
**Is your feature request related to a problem? Please describe.**
When someone new decides to contribute a helpful messages can be sent to them such as `Hi/Hello Thank you for contributing. Please run spotlessApply to make sure the code is clean` An example can be seen [here](https://github.com/YusufsDiscordbot/Yusuf-s-Moderation-Bot/blob/JDA-Development/.github/workflows/greetings.yml)

**Describe the solution you'd like**
A GitHub actions would be triggered if the contributor is contributing for the first time

**Comment by RealYusufIsmail** [comment]
If approved I will work on it

**Comment by Tais993** [comment]
I'd prefer it if we just add it to the PR template.

Where link is a link to the wiki on spotless

See:
- [ ] Code has been formatted by spotless (link)

**Comment by RealYusufIsmail** [comment]
I dont get what you mean.

**Comment by RealYusufIsmail** [comment]
Do you mean the contributor gets a welcome message which includes the wiki link

**Comment by Zabuzard** [comment]
> I'd prefer it if we just add it to the PR template.

Agreed. I dont really see the benefit of reminding about spotless itself in particular though. It is already part of the checklist of the PR (not the template, but at the bottom of the UI). So in my eyes this would be obsolete. And Spotless is also not the only check that is executed, there are multiple and they might also change over time. Instead of adjusting the PR template or a welcoming message, I would just use GitHubs existing UI that makes it already pretty clear what checks are executed and what not.

On top of that, we added majority of checks to `gradle build` and `gradle run`, so if people actually test their code locally, simply building and executing will already auto-run the checks. It is not easy to miss the fact that we are running tests.

Also, the author of a PR gets notifications if the tests fail, including the test failure reason.

Summarized: Voting to discard this issue cause obsolete.

**Comment by Zabuzard** [comment]
> I dont get what you mean.

When you create a new PR, the description text of the PR contains a template text, which contains a checklist already. See:

https://github.com/Together-Java/TJ-Bot/blob/develop/.github/PULL_REQUEST_TEMPLATE/feature_add.md

**Comment by RealYusufIsmail** [comment]
Oh ok.

**Comment by RealYusufIsmail** [comment]
When i create a pr there is no template 
<img width="946" alt="Screenshot 2021-12-05 at 10 19 05" src="https://user-images.githubusercontent.com/67903886/144742505-935c5df1-c76d-4637-b7aa-e06b71c662b7.png">

**Comment by RealYusufIsmail** [comment]
I will start work on it

**Comment by Zabuzard** [comment]
I am still voting against changing the PR template. If its broken, fix the bug but dont change the content of the template, in my opinion.
