### ISSUE TITLE
Make free-systems welcoming message ephemeral

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#305]
Each time a user posts a question in a free channel, everyone sees this welcoming/explaining message:

![message](https://i.imgur.com/CaKkcBE.png)

For other members, this contains no useful information. It is also annoying to helpers since they will read this many times per day. And additionally, it distracts and removes attention from the actual question, as it is posted below the actual question.

All in all, I am voting for making this message **ephemeral**, so that only the author can see it. Any objections? (@borgrel )

**Comment by borgrel** [comment]
i think this should be done
but i dont think it should be done immediately

i figure if the users dont get to see the message arriving for about a month
when they watch other users use the free channel (or scroll up)
they will completely freak out when they get it
we cant expect our beginners to know about ephemeral messages, etc

so keep it visible for now and it can change later

also since it seems like the next step that everybody wants is the free system switching to a thread based concept
the message will get much simpler (no need to tell ppl not to spam channels because the bot will control thread creation so they cant post it in multiple channels

**Comment by borgrel** [comment]
Another problem to consider is that that message is a response to a `guildMessageRecieved` event
which is not an interaction, so the response message cannot be made ephemeral

you will have to trick up some imaginary interaction to generate an ephemeral reply

**Comment by Zabuzard** [comment]
Good points. I am discarding this then for:

1. technical difficulty
2. unclear if needed in the near future at all
3. unsure if actually useful or causes confusion
