### ISSUE TITLE
create issues for closed #tj-suggestion threads that have been approved

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#307]
**Is your feature request related to a problem? Please describe.**
more than 27 suggestions where made and discussed in #tj-suggestions (discord) and nobody knows which ones have been approved, which ones have been implemented, which ones will at some point be implemented, which ones have been denied, etc

nobody is monitoring the suggestions and creating a list of suggestions that need to be implemented.

**Describe the solution you'd like**
keep track of features that need to be implemented
make it clear to the users which suggestions have been accepted, which ones have been accepted with alterations and which ones have been declined with reasons for the denial)

**Comment by marko-radosavljevic** [comment]
You want them here, on the github, as an issue? That's a weird UX, going from discord, where the suggestion was made, to searching github issues… Also, extra work for the mods/bot.

You are correct that our current method of dealing with suggestions is not ideal. I react with :correct: (green checkmark) when a suggestion is implemented, and do nothing with suggestions that don't have enough votes.

Since suggestions are thread-based, and much cleaner now, it's easy to monitor them. One of the more straightforward solutions would be for a mod to comment on the thread, the final decision. And then either add `[APPROVED]` tag in the name, or react on it, for visibility. What do you think about that?

So threads would be archived, not cluttering the UI. And with just a glance at suggestions, you would see what's implemented, approved, rejected, etc.

**Comment by Zabuzard** [comment]
I think we can definitely already go with `[APPROVED]`, `[DECLINED]` name-tags for now. Even if we still maybe want to add bot support to improve something here (or not), such tags would be helpful already, I guess 👍

**Comment by marko-radosavljevic** [comment]
Agree, will do that in the meantime. ^^
