### ISSUE TITLE
Plethora of ideas.

### ISSUE THREAD

**Issue by ryan-sam148** [Together-Java/TJ-Bot#388]
**Template has been completely removed since this issue is a feature request not a bug report. Please fix this issue **asap**.**

**Ideas**:

- Language Translator; Uses google translates api `java-google-translate-text-to-speech`@latest. i could find an IBM alternative, after the idea has been approved by all parties. slash command builder `/trans "abri kedabri"` -  `/trans -10` - `/trans` detected lang / prefix match to auto detect / use googles own detector(**worst idea**). Seconds is an index system, finds 10 msgs, without the current msg translates them all. 

- Social credit points; a meme but a good one. can be used in the ranking system. top helper etc....

- Music night; bot starts disco (rap songs etc...) `4:30 PM - 6PM UTC` time will not be changed. most admins are on at this time , and chat is commonly active. nice to have some sound while coding. you can listen to new songs etc... ; disco rapper picks the songs, based on voting system. 

**IDEAS WILL BE IMPLEMENTED BY MYSELF!**

also please be nice its my first time here.

**Comment by Zabuzard** [comment]
* Language Translator - interesting idea. But Discord already has a text-to-speech functionality (right click message > speak message). So your suggestion is kinda obsolete.
![speech](https://i.imgur.com/FwCcQRp.png)
* Social credit points - I do not quite get this. On what should we give out credits? The biggest issue with credits in any form is inflation, which is also why we didnt add a score or thank-you-points system.
* Music night - most music bots have been banned due to copyright issues. there is almost no proper music bot left anymore. doing it ourselves sounds like opening pandoras box, unfortunately.

**Comment by Heatmanofurioso** [comment]
Regarding the copyright issue @ryan-sam148 
One thing is for you to enjoy content, another is to share it in a platform. Quite different if I use my Netflix account, or if I stream stuff off it for others to see for free. Among many other reasons & examples

**Comment by Tais993** [comment]
> I don't like soundcloud since its all remixes.

Maybe there's also remixes on there, but it's not "all" remixes

Spotify doesn't have a way to listen to music, so no.

audiodb doesn't have songs on there, just info from what I can see, correct me if I'm wrong

And I doubt that API gives the songs either.

You just need a site that has a way to get the file, whilst it's legal
If you're gonna use [Lavaplayer](https://github.com/sedmelluq/lavaplayer), see below what it supports
Supported != legal*
>>> 
    YouTube
    SoundCloud
    Bandcamp
    Vimeo
    Twitch streams
    Local files
    HTTP URLs

Filetype:
>>> 
    MP3
    FLAC
    WAV
    Matroska/WebM (AAC, Opus or Vorbis codecs)
    MP4/M4A (AAC codec)
    OGG streams (Opus, Vorbis and FLAC codecs)
    AAC streams
    Stream playlists (M3U and PLS)

**Comment by marko-radosavljevic** [comment]
> > Social credit points; a meme but a good one. can be used in the ranking system. top helper etc....
> 
> Don't think we need it

Eh, our current top helper system is a bit too naive, tbh.

Top helpers shouldn't be people that can spam the most messages, but people that are.. well... top helpers :D

We could add a couple more factors to the calculation. Just message count is a bad metric imo, especially if you literally count message number instead of character count (some people send lots of short messages, some send full paragraphs).

We could have this in combination with thank-you-points system, that resets monthly to avoid inflation. The issue with these other systems is that they can also be unfair quite easily.

For example, very friendly helpers will have a big edge within thank-you-points system. Which can be actually a good thing, since it incentivizes friendliness on the server. This is the biggest reason why I would consider addition of alternate systems; improving quality of the help on the server and member satisfaction. Could also be a useful metric in evaluating help on the server in general, and further improvement.

Also, average helper doesn't have enough interactions for this system to average out fairly. What can happen is a helper spending 4h on one member, without getting any points for a thorough and high-quality guidance. So on low sample sizes, it's very lacklustre. 

But adding more factors to the current system can make it more fair and generate better outcomes. Now, issue is, it's hard to design such systems, a lot of care and consideration needs to go into it. I would like to see what people can come up tho, since I'm convinced the current system can be improved. ^^

**Comment by Zabuzard** [comment]
The music suggestion is a dangerous topic. Its probablly better to not go down this rabbit hole. In particular since we dont VC  that much either, not worth it.

The translation command is a good idea if it translates **ephemeral**. Our server language is and will stay english-only. So the command should not post any non-english text. But it is a cool idea if it offers non-natives the ability to translate something for them if needed. I.e. `/translate message-id:<id_of_message_to_translate>` and then pops a **ephemeral** message to the author with the translated text. It depends a bit on the API plan of googles API though. Not sure what the free options are, we do have a dedicated TJ-Bot google account for such things though.

**Comment by ryan-sam148** [comment]
Sure! I'll get to work on the translation system, and test. thanks to everyone for giving these awesome suggestions ! Very warm welcome too! :)
