### ISSUE TITLE
Dont react on "created thread" in suggestion channel

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#401]
### Overview

As of now, the bot pretty much reacts on anything in the suggestion channel. That is generally not bad, but it also includes the meta-messages that an user created a thread, see here:

![thread](https://i.imgur.com/5RfQTtH.png)

The bot should not react on those. Maybe we could even remove them to keep the chat history cleaner (but thats another story).

**Comment by marko-radosavljevic** [comment]
I'm leaning towards removing those messages, since I haven't found them useful at all. They just add noise and clutter to the suggestions.

But I check suggestions often, and scroll back and check old threads on a weekly basis. Also, I usually participate in them, and they are on my sidebar, so I don't miss any discussions. Maybe it's useful for members that check or participate in them less frequently? So they get a notification message that there is a new discussion on some old suggestion?

I personally dislike them, but wouldn't want to reduce visibility of active discussions, that would hurt the whole process. We want more people participating, not the other way around.

What mechanism is there to let other members know discussion is happening on an older suggestion? It doesn't appear on your sidebar, since you are not participating, and I don't think anyone is checking the thread view… So thread and discussion being opened is completely invisible to most?

I guess we just remove reactions for now. :relaxed:

**Comment by Tais993** [comment]
I don't understand how they're useful, you can't create multiple threads on the same message.
Below a message you can literally see the thread, see 
![image](https://user-images.githubusercontent.com/49957334/156131073-2ccb3d1f-fdc0-4dce-bf33-70b251d38bf6.png)

People can join threads by looking a the message & by the thread view.

Right now it's just random messages that lack context, and due to people giving threads really bad names, I rather have them gone. So they should be removed, unless an actual valid reason comes in.

**Comment by marko-radosavljevic** [comment]
Yeah, If you can see the suggestion and thread it's useless, those messages don't even show if you create a thread on the most recent post.

I believe it's purpose is to notify you that there is a thread being open on some old post. Because most people won't scroll and check each past suggestion on the daily basis, they would never notice the new thread/discussion.

So let's say I wanted to start a conversation about this suggestion (no thread attached to it, 2 weeks old, so it's buried):
![image](https://user-images.githubusercontent.com/30927961/156169328-f06d6170-aa50-4140-9e69-86c93baa6368.png)
I create a thread, start discussing it, but nobody sees and joins it. :(

So something like `not marko
 started a thread: Transition to thread model for high quality channels` with a link to it helps.  People can be like oh, I have an opinion about threads, and join the discussion.

* * *

But for me personally, they are annoying and just add noise, since I check them frequently, and I'm aware of all discussions. I would like to get rid of them, but wouldn't like to hurt visibility on new discussions for others.

**Comment by Zabuzard** [comment]
Closing in favor of #468
