### ISSUE TITLE
Replace red/green circles from help system (colorblind accessibility)

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#409]
## Overview

Our help systems status message uses 🔴 and 🟢 , which are hard to distinguish for people with red/green colorblindness. We should replace them with icons that also add a different shape.

![status message](https://i.imgur.com/7FbXQS4.png)

The relevant file is `ChannelStatusType.java`.

**Comment by Tais993** [comment]
I don't understand why you went for a stop-board, why not use ❌ and ✅? 
A stop-board is only recognizable because of it's colour, unlike a X

**Comment by Zabuzard** [comment]
It was an example. Details can be figured out in the PR. Ill take ur comment as CR and change it.

**Comment by Zabuzard** [comment]
(done)

**Comment by borgrel** [comment]
isnt colour blindness support implemented by remapped colours on an OS-level

people with colour blindness should already have support and already know how the operate the accessibility options in their chosen OS and should already have the colours that are a problem for them remapped to other appropriate colours (since everybodies colour blindness is differant)

as soon as u change it from colours to symbols you get the problem that symbols need to be interpretted:
does a tick mean the channel is occupied or does it mean that its available? plenty of ppl will think it means the one way and plenty will think it means the other

also the symbols will be less visible on lower resolutions and from further distances meaning that ur preventing ppl from using their cellphones or watching their screen from across the room waiting for a symbol to change

your making it worse for everybody to give no reasonable change for what u claim to be helping

its like installing handicapable controls on every car on the planet, not only does it not help, because each individual needs the controls structured in a manner unique to them, but u make driving less safe to the 99.99% who need to use the car normally and there will be tons more accidents as they try to operate the vehicle around the useless controls. While this change wont kill anybody its still just as invalid.

**Comment by Zabuzard** [comment]
In general, I agree to that. But I think ✅ & ❌is actually good enough for people with good vision as well. Maybe even better, since it adds distinct shapes - so even people with good vision can differentiate it easier and faster at first glance.

**Comment by Tais993** [comment]
> as soon as u change it from colours to symbols you get the problem that symbols need to be interpretted:
does a tick mean the channel is occupied or does it mean that its available? plenty of ppl will think it means the one way and plenty will think it means the other

I doubt, a red cross gives someone a "no" not a "yes", I've never seen someone think a stop-sign means they don't have to stop. But to make sure we can add a legend

> also the symbols will be less visible on lower resolutions and from further distances meaning that ur preventing ppl from using their cellphones or watching their screen from across the room waiting for a symbol to change

This doesn't make a lot of sense, where are you basing this from?
Before the only thing to change was the colour, now the shape AND colour change.
So why would this become harder? The colour is still there.

> your making it worse for everybody to give no reasonable change for what u claim to be helping

Making what worse? 

> its like installing handicapable controls on every car on the planet, not only does it not help, because each individual needs the controls structured in a manner unique to them, but u make driving less safe to the 99.99% who need to use the car normally and there will be tons more accidents as they try to operate the vehicle around the useless controls. While this change wont kill anybody its still just as invalid.

It's more like installing handicapable controls to every car, that you don't notice until you enable them.
Your downsides lack arguments, so I'll discard them personally until you elaborate on what you are basing everything on.

I see no downsides, only upsides.
