### ISSUE TITLE
Add /pin-help-message command

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#486]
Sometimes it can be useful to be able to pin messages in a help thread. Unfortunately, Discord permissions are not granular enough to grant such a permission to our users without giving them too much power.

The solution would be a dedicated `/pin-help-message <message_id>` command that can pin a given message.
* the command should only be usable in help threads (see `/change-help-title` which has such a check already)
* the `/tag-manage` commands can be used as example for commands working with a `<message_id>`

Ideally this command could be a made a context command (right click message > pin ...), but we need JDA5 for that first.

**Comment by marko-radosavljevic** [comment]
Not sure how needed this feature is, maybe you can give me a few use-case examples?

It's not that common, but there are some long-lived threads, and in those cases a feature like this _might_ be handy. Where multiple helpers reengage during multiple days, and pinned message could save some time.

But there are a lot of _ifs_, if the thread is long-lived, if the message worthy of a pin exists, if the helper bothers with pinning the message, if anybody else bothers to check the pinned messages for that specific thread..

The biggest issue is the UX of copying the message id, and then typing out the command just to pin a single message. The feature would be much more useful with context command, like you mentioned, since then cost is low, and you can pin everything you might want to reference in the future, OP's code or your explanation.

So I vote for waiting for JDA5 and then doing the context command.

* * *

Maybe we can pin the first message (actual question) by default, so you don't have to scroll to the top if you forgot what it is about. And maybe we can automatically pin all code blocks OP posts, since those are usually the most referenced and important 'checkpoints' that you always go back to, to copy or reply to.

So possibly with some automation, pinning becomes easier and more useful?

**Comment by Zabuzard** [comment]
I had the same thinking and the "pin first message" is another issue #479 . This one specifically came up as a suggestion in our Discord and someone reasoned that he occasionally would liked to have such a feature. Personally, I dont need it.

**Comment by Taz03** [comment]
can this be a context command, i feel like this is best suited for a context command

**Comment by Zabuzard** [comment]
yes. but we only have 5 slots available... :(

**Comment by Taz03** [comment]
> right now im more tending towards dropping this all together

what will be the solution then, give members pin permission?

**Comment by Zabuzard** [comment]
yeah. or not have it at all? is it really needed/wanted? iirc it was a single user asking for it and they even said that they dont actually need it.

**Comment by Taz03** [comment]
> is it really needed/wanted?

i personally don't feel like this is a feature i'll use, but it has the valid tag so idk, its on u to decide

**Comment by Zabuzard** [comment]
lets close it for now until someone asks for it again 🤷
