### ISSUE TITLE
Group the help thread commands

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#532]
# Group the help thread commands

by using sub slash commands and slash command groups

```
/help-thread change title
/help-thread change category
/help-thread close
/help-thread pin-message
...
```
Advantages:-
1. It is clear that these commands are help-thread commands and will only be used there
2. Easy to maintain (e.g. only one command to set to help threads in discord integration settings)

**Comment by Zabuzard** [comment]
When creating the commands initially, I thought about that as well. But then thought its easier for the user if the command starts with the actual word they want to use. I.e. `/change...`.

At that point there was only one command though `/change-help-category` and not 2 or 3.

I am still unsure though. The commands should be as simple to use as possible. So priority is on the UX and not on how nice they are to maintain in code. For `1.`, id like to note that the commands are already only visible in help threads, since Discord allows to set that in the integration settings.

All in all I am unsure about this. Other opinions?

**Comment by Taz03** [comment]
> When creating the commands initially, I thought about that as well. But then thought its easier for the user if the command starts with the actual word they want to use. I.e. /change....

I mean they can still get the command pop up when they do that for example this tag manage command with a create sub command will pop up when i only write create
![image](https://user-images.githubusercontent.com/73871477/186603901-c6822b4c-7036-4d90-a70b-916b5f55833f.png)

**Comment by Zabuzard** [comment]
Fair. Sounds good to me.

**Comment by Zabuzard** [comment]
@Taz03 Since you tagged it **good first issue**, please outline in the description which files to touch, what to do and where one can find examples.

Just because something is simple, doesnt mean its directly beginner friendly. Gotta give some outline and help.
