### ISSUE TITLE
Modify ImplicitAskListener 

### ISSUE THREAD

**Issue by mikerasch** [Together-Java/TJ-Bot#569]
## Problem
People simply do not like to read. While the current method of this class serves a great purpose, people frequently fail to adhere to the bot postings after the thread is created. This causes the problem where it lacks either a title and/or category resulting in an empty thread. While this might not seem awful, it frequently happens and might sway away people from our discord. 

## Solution 
Modify ImplicitAskListener to not create a thread, but rather inform the user about the wrong interaction. This can be done by removing everything but notifyUser() and tweaking onMessageReceived(). Changing the message to something along the line as "hey use /ask {title} {category}.

Delete ImplicitAskListener and force the user to read the channel and correctly interact using /ask {title} {category}.

## Alternative
On the creation of an ImplicitAskListener thread, mention to the user the steps he/she must make in order to finalize the creation of the thread. I believe there was a PR about this not long ago. While this might be a good solution, a good number of people who fall into the previously mentioned mistake simply never follow up. Leading to a waste of a help thread.

## Additional Points
If this was to be implemented, I think modifying ImplicitAskListener would be the better option. Deleting altogether will not solve the problem of people not reading. While modifying at least instantly grabs their attention and there might be hope.

**Comment by Zabuzard** [comment]
I dont like this suggestion. It increases entrance barrier for new users who dont read the explanation.

You might want to argue that they didnt deserve better and should learn to read. While I do agree to that, at the end of the day it is the server/community who has to pay the price of having a worse retention rate and decreased growth.

---

I favor solutions where the bot approaches the users in hindsight and tells them what to do instead. For example, uncategorized threads are a thing from the past since #487 has been merged. It was a huge success, I havent seen any uncategorized channel anymore since then.

Regarding not posting any question/details, we have #481 , which hopefully is implemented soon.

After thats done, maybe the problems are gone already? 🤷

**Comment by mikerasch** [comment]
> I favor solutions where the bot approaches the users in hindsight and tells them what to do instead. For example, uncategorized threads are a thing from the past since #487 has been merged. It was a huge success, I havent seen any uncategorized channel anymore since then.
>
> Regarding not posting any question/details, we have #481 , which hopefully is implemented soon.
>
> After thats done, maybe the problems are gone already? 🤷
I wasn't 100% sure, but I did see the bot message in a channel about the help category. Seems like a great first step.

Could we maybe implement another message for something like when users leave a title as "untitled"? 

I will leave this discussion available for a little bit just to see if some people want to chime in and maybe suggest more additions.

**Comment by Zabuzard** [comment]
> Could we maybe implement another message for something like when users leave a title as "untitled"?

Absolutely. In fact, I would even add such a reminder for all threads that were created with `ImplicitAskListener`.
