### ISSUE TITLE
Add user-context-commands for Moderation

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#593]
## Overview

We just got hands on `UserContextCommand`s, they are cool. And ideal for most moderation commands. We should add duplicates of the existing slash commands for them:

* [x] ~~ban~~
* [x] ~~unban~~
* [x] ~~kick~~
* [ ] warn
* [ ] mute
* [x] ~~unmute~~
* [x] ~~audit~~
* [ ] note
* [x] ~~quarantine~~
* [x] ~~unquarantine~~
* [x] ~~whois~~

It is totally okay (and to be expected) if this addition is done step by step, PR by PR.

## Slashcommands

This is not supposed to replace the existing slash commands, we still need them. Moderators must still be able to ban users (and similar) by just knowing the ID of the user.

## Duplication

How to tackle the obvious code duplication is up to the implementor. But in most cases, it is probably easiest to simply have two slim commands that directly forward to a common class. Such as:
* `BanSlashCommand`
* `BanUserContextCommand`

and both just forwarding to a
* `BanCommand`
class, which has all the actual logic.

This obviously bloats the code base a bit. To tackle it, the classes could maybe be nested in `BanCommand` and not have their own files.

**Comment by Taz03** [comment]
we can only have 5 user context commands, no?

also i feel like these commands are ok as slash commands, when we can tag a user directly in a slash command

**Comment by Tais993** [comment]
Limit is indeed 5, so we gotta prioritize which commands we want.

**Comment by Zabuzard** [comment]
oh lol what. i wasnt aware. is there also a limit on message context?

**Comment by Tais993** [comment]
Also 5

**Comment by Zabuzard** [comment]
thats a big oof. how does it behave when going beyond the limit? crash? exception? silence? logs?

**Comment by Tais993** [comment]
It's simply

You can only register 5, if you exceed this limit JDA will error. Alternatively Discord errors.

Permissions don't matter, or anything.

It'll result in the commands not being updated and an error, it won't crash the bot.

But this limit is something we'd notice before we get there.

**Comment by Zabuzard** [comment]
alright. im voting for:

* warn (only mods)
* mute (also ambassadors)
* note (also ambassadors)

im thinking of what are the most crucial commands to have at hand when shit goes down:
- mute the user so that they cant do harm anymore

commands that are used most frequently by mods:
- warn

and commands that i want to see being used more frequently, also by ambassadors:
- note

**Comment by Taz03** [comment]
> mute (also ambassadors)

just timeout the user instead, when u already opened the right click menu

**Comment by Zabuzard** [comment]
@Taz03 our mute does more than discords timeout. its not obsolete yet.

**Comment by Taz03** [comment]
but, we'll only left with 2 more user context commands then :c

**Comment by marko-radosavljevic** [comment]
> @marko-radosavljevic ur opinion on this?

Yeah, I agree. It's not like we have many candidates for user commands, and I have the same reasoning, and would pick the same 3 moderation commands.

Ideally, it would be nice to have /note and possibly /warn as a message command, same with /report, even though it might seem counter-intuitive. Usually, when you report or write a note, you are noting a specific offensive behaviour at the specific point in time. Context is important, and you can't summarize the whole interaction in a single line comment. Having a message ID, so you can jump to the interaction and check what exactly happened even years after the fact, is powerful.

For example, I might note:
`Insulted a member, was verbally warned.`

Now, for moderation documentation purposes, this is not as useful as it can be, since you don't have the whole context of 1 hour argument, and how offensive and toxic someone actually was. And finding that context after a few months or years is nearly impossible. So I usually post links to the interaction, but often I'm too lazy to document everything in such detail.

This would make noting extremely low effort, just right click and few words. But at the same time very powerful, because you get an interaction link automatically, so it's self-documenting in a way. And if you ever need more information in the future, you can easily verify it yourself.

Message context command or not, I think having note on right click is nice, and would help us all use it more frequently.

On that note, I discovered today that you can mention a member while writing a slash command, so you don't have to do right-click and copy id. This is really nice because you don't have to touch your mouse at all, ctrl+k and jump to commands channel and start typing and auto-completing right away.

* * *

This is much more important for the /report command. For example, if we get:
"click insulted me"

This is not helpful at all, and we have to do a lot of work to actually verify it.

1. Who is click, and which click exactly? I have to search for their ID, do whois, and what to do when there are 3 users named click?
2. Did they actually insult them? When did they do that? Now I have to scour the logs in past 10 days, to find if it actually happened
3. If I don't find anything, I have to search in logs of deleted messages, which are massive..

But to require all this information (user ID, message ID) from the user with a slash command is extremely unfriendly. And you can't reply to the offensive message and use a slash command either. So I think message command is a logical choice here.

* * *

Now, of course, I understand that we have a lot of good candidates for the message commands, and not that many for user commands, and that we are fairly limited in that regard.

**Comment by Zabuzard** [comment]
closing this due to the limit. we will soon get report anyways
