### ISSUE TITLE
Create FormatCommand

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#621]
## Intro

We have a code formatter side project, example usage:

```java
String input = "..."; // some code

Lexer lexer = new Lexer();
Formatter formatter = new Formatter();
String result = formatter.format(input, lexer);

System.out.println(result); // nicely formatted
```

We should finally attach this functionality to the code base.

## UX

It could be a message context command for starters, but even better could be if we auto-detect code and then send some sort of message with buttons:

> Code detected. Here are some tools:
> [Run] [Format] [View Bytecode]

For now, only the `[Format]` button would be there.

Care must be taken to only run the formatter on actual code, so we have to detect and extract contents of code-blocks \`\`\`java ... \`\`\`. The #207 PR can be checked for a REGEX to do so.

When the button is clicked, the bot would send a message with the formatted code.

It would also be cool if the message auto-updates whenever the original code was edited (see #207 which does that as well).

## Code style

The `Formatter` project is in a rough shape right now and the whole project needs serious improvements. This should be done by someone familiar with clean coding techniques, its not trivial.

**Comment by marko-radosavljevic** [comment]
I really like the UI/UX idea! :heart: 

Ideally, formatting should be applied automatically, if the feature is stable and there are no issues.

However, detecting code and formatting deterministically is not trivial. Especially on random uncompleted code, that doesn't compile, has text question attached to it, doesn't start with `class` etc.

Because of that, giving it a test run before doing it automatically is probably a good idea. Being able to post code is a critical requirement for our server. So I would suggest a button with no *auto-update on edit/delete* for now, to pick the least destructive path if something goes wrong. Or some other fail-safe undo mechanism, so the original user posed code is never lost.

**Comment by Zabuzard** [comment]
Yeah. My observations are that the tool isnt good at all at formatting mixed content. Its only good at formatting code-only stuff. So right now I am extracting stuff out of java-code-blocks only. And then sending it as a new message. The original message isnt deleted.
