### ISSUE TITLE
Remind to use /bump 1x week

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#666]
About once in a week, mods/community ambassadors have to use two `/bump` commands to bump us in popular server discovery websites:

![bump](https://i.imgur.com/SsWPYwG.png)

It would be helpful if the bot can send a reminder, maybe each Tuesday ~11:00 CET. The reminder can be send in the `#community_commands` channel (probably needs a dedicated config entry `remindBumpChannel: ...`).

Ideally, the reminder could also mention both slash commands, so that we only have to click on them (see `MessageUtils.mentionSlashCommand`). But this part is optional.

It is probably not needed that we blow this feature up into something bigger and more abstract. A simple hardcoded reminder for this one use case should be enough.

**Comment by marko-radosavljevic** [comment]
I think we should just create a culture of bumping, and let more people bump, since until recently only mods could do it. I'm positive we would have at least 1 bump a day with relaxed permissions, and maybe one PSA about it, or more public bumps, so people can see it. Because even tho bumping is hidden from the majority of the server, people tried to bump, but figured out they don't have the perms.

Also, 1 week is a lot of time, the more bumps we can fit in a day, the better. For example, on disboard, if you search for `java`, we are not in the first 3 pages (about 70 results, I haven't looked past that). For `java programming`, we are on 10th place, you have to scroll for it, and it was already bumped today. After a whole week, we would be completely buried.

**Comment by Tais993** [comment]
You can bump every 3 hours / 2 hours, so yeah, 1 week is far too slow tbh

**Comment by Zabuzard** [comment]
What does this mean for this suggestion in your opinion? Keep it, but adjust to maybe a reminder at 8:00, 12:00, 16:00 ?

Or completely drop it?

**Comment by marko-radosavljevic** [comment]
I personally think it's a "wrong" solution to the problem we are facing. Bumping shouldn't be a chore, but something we volunteer because we like the server. It can also be satisfying because it's an easy task to do, and you feel good/productive about it, so it's something people do without you needing to force them.

Let's wait a bit, and see how it goes. I'm positive that relaxing the perms and social encouraging is all we need.

Ultimately, I don't really mind a subtle and non-spammy reminder. :relaxed:

**Comment by Zabuzard** [comment]
i just saw myself constantly forgetting about it, cause nothing reminded me.

**Comment by Zabuzard** [comment]
Closing for now, might get reopened if it actually turns out as necessary step.
