### ISSUE TITLE
Activity updater bugged

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#707]
https://github.com/Together-Java/TJ-Bot/blob/b80feef2b1f54d51d3fc1b85e0569d0c4d743443/application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java#L84-L87

Sometimes ppl write short messages and it hits the limit, and the bot decides to put the `SEEMS_GOOD` sign even before anyone opened it, rn its just the author. Also the bot sends 2 messages in each thread so its really easy to hit the limit without any helper sending any message.

I'd say do the number of authors check for this too, i.e only mark it `SEEMS_GOOD` after some helper really replied.

https://github.com/Together-Java/TJ-Bot/blob/b80feef2b1f54d51d3fc1b85e0569d0c4d743443/application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadActivityUpdater.java#L89-L95

The impl is simple just add one check more

**Comment by Zabuzard** [comment]
The problem is that you just have to mark it SEEMS_GOOD once you went over a certain message limit. There is no way around that.

Imagine a thread with 1 million messages. And the authors message is the 1_000_001 message (one after). You can not know that. You have to give up at some point. Otherwise you would need to retrieve all message history. And that hits rate limits.

The activity updater is executed every minute for each active thread (usually ~50). In order to not stress our rate limits, we have to keep the amount of messages looked up fairly low.

Hence the feature is only allowed to lookup a few messages and has to work with the information it got there.

Now, if you do not write "SEEMS_GOOD" beyond that limit, and OP did not write within the limit yet, there would be no way to set the thread to SEEMS_GOOD anymore. It would then stay with the current activity forever.

**Comment by Taz03** [comment]
understandable :+1:
