### ISSUE TITLE
Use Maven or Gradle?

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#8]
Should we use **Maven** (🚀) or **Gradle** (🎉) as build tool?

React with the corresponding emoji to vote.

**Comment by illuminator3** [comment]
gradle ftw. maven can be really hard to read sometimes because of xml. it's also really hard to do dynamic stuff in maven.

**Comment by d3vel0per** [comment]
Also maven has a lot of moving parts. Like the compiler plugin itself has separate versions in addition to maven itself.
It can become confusing to new comers.

**Comment by I-Al-Istannen** [comment]
Maven is simple, you only have an XML structure we already provide and adding dependencies and stuff is just copying a small block. In exchange for that you get a rock-solid tool that doesn't do any surprising things during build.


Additionally, in my experience, courses often use maven so that might be an additional advantage.

**Comment by Tais993** [comment]
> Maven is simple, you only have an XML structure we already provide and adding dependencies and stuff is just copying a small block. 

This could also be said about Gradle

> Additionally, in my experience, courses often use maven so that might be an additional advantage

For adding dependencies, I always see Maven + Gradle.
Regarding courses, it doesn't matter really, it's the same for Gradle.

**Comment by marko-radosavljevic** [comment]
> Additionally, in my experience, courses often use maven so that might be an additional advantage.

It really depends, both are very widely using, and more and more people are converting to gradle these days. Editing or optimizing build scripts is not something I would expect a newcomer to do. One line copied from mavencentral is everything you should know about gradle as a newcomer.

Adds a lot of flexibility and control at a cost of slight complexity increase. Worthwhile trade for me, but ultimately I'm fine with both tools. ^^

https://gradle.org/maven-vs-gradle/

**Comment by krankkkk** [comment]
> Maven is simple, you only have an XML structure ...

I wouldn't say that XML is really readable for an beginner, but especially the Kotlin-variant of Gradle is easily understood.

> ... adding dependencies and stuff is just copying a small block. ...

So is it for Gradle.

> In exchange for that you get a rock-solid tool that doesn't do any surprising things during build. 

Once again, so is Gradle.

> Additionally, in my experience, courses often use maven so that might be an additional advantage.

While there might me an huge amount of tutorials with maven, there are more recent tutorials on Gradle simply because Gradle is the newer tool.

**Comment by java-coding-prodigy** [comment]
Simpler to add external libraries in Gradle.

**Comment by LovinLifee** [comment]
I would opt for Gradle.

**Comment by Zabuzard** [comment]
We will use **Gradle** until the community decides otherwise.
